Adds initial files with basic funcitonality
mlcpp/heterovector pull request #1
Opened 2021-04-10 05:11 UTC by aniketsharma00411

Basic functions for heterovector are added.

cmake files are also added to compile and run example files.﻿

2021-04-10 13:43 UTC, ashok-arora requested changes

2021-04-10 13:43 UTC, ashok-arora commented on include/heterovector.hpp
> +#ifndef _Matrix_hpp_
Change this to heterovector

2021-04-10 13:52 UTC, ashok-arora requested changes

2021-04-10 13:52 UTC, ashok-arora commented on include/heterovector.hpp
> +    return std::get<T>(vec[index]);
std::get can throw std::bad_variant_access exception, consider using a try catch block.

2021-04-10 13:53 UTC, aniketsharma00411 commented on include/heterovector.hpp
> +#ifndef _Matrix_hpp_
Sure 😆

2021-04-10 13:58 UTC, aniketsharma00411 commented
I have done the changes. Check again

2021-04-11 14:29 UTC, ashok-arora approved these changes
Looks good to me.

2021-04-11 14:29 UTC, merged